version: "3.2"
services:
  influxdb:
    build: influxdb
    env_file: configuration.env
    ports:
      - '8086:8086'
      - '0.0.0.0:2003:2003'
    volumes:
      - ./data/influxdb:/var/lib/influxdb
  grafana:
    build: grafana
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./data/grafana:/var/lib/grafana