{
 "title": "Generator metrics",
 "description": "This dashboard json is from https://github.com/botleg/swarm-monitoring. I did nothing! Because there isn't the json file in grafana homepage, I upload by myself :D",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Usage total {$tag_machine, $tag_container_name}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "machine" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "cpu_usage_total",
     "query": "SELECT derivative(mean(\"value\"), 10s) FROM \"cpu_usage_total\" WHERE (\"container_name\" =~ /cadvisor/) AND $timeFilter GROUP BY time($interval), \"machine\", \"container_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 1000000000 * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/cadvisor/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_machine, $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "machine" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "memory_usage",
     "query": "SELECT mean(\"value\") FROM \"memory_usage\" WHERE (\"container_name\" =~ /^$container$*/ AND \"machine\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"machine\", \"container_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/cadvisor/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "RX {host: $tag_machine, container: $tag_container_name}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "machine" ], "type": "tag" }
     ],
     "measurement": "rx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "cadvisor_cAdvisor_1" }
     ]
    },
    {
     "alias": "TX {host: $tag_machine, container: $tag_container_name}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "machine" ], "type": "tag" }
     ],
     "measurement": "tx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "cadvisor_cAdvisor_1" }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Usage {host: $tag_machine, container: $tag_container_name}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "machine" ], "type": "tag" }
     ],
     "measurement": "fs_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "cadvisor_cAdvisor_1" }
     ]
    },
    {
     "alias": "Limit {host: $tag_machine, container: $tag_container_name}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "machine" ], "type": "tag" }
     ],
     "measurement": "fs_limit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "cadvisor_cAdvisor_1" }
     ]
    }
   ]
  }
 ]
}