{
 "title": "gatling",
 "description": "Gatling load generator monitoring dash board",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ROOM usres",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "ROOM_Scenario" }
     ]
    },
    {
     "alias": "WHOLE users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "WHOLE_Scenario" }
     ]
    },
    {
     "alias": "TEAM COLOR users",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "TEAMCOLOR_Scenario" }
     ]
    },
    {
     "alias": "IDLE users",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "Idle_Scenario" }
     ]
    },
    {
     "alias": "Mobile WHOLE users",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "Mobile_WHOLE_Scenario" }
     ]
    },
    {
     "alias": "Mobile IDLE users",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "Mobile_Idle_Scenario" }
     ]
    },
    {
     "alias": "All Users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allUsers" }
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "All req",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(count) FROM \"gatling\" WHERE $timeFilter AND \"request\" != 'allRequests' AND \"status\"='all' group by time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Error APIs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ko' AND \"count\" > 0) AND $timeFilter GROUP BY request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors v Passes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "All Passes",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "query": "SELECT mean(\"count\")  / 2 FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "All Errors",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "query": "SELECT mean(\"count\")  / 2 FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ko') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Latency time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "percentiles50",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "query": "SELECT mean(\"percentiles50\") FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'all') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "percentiles50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "percentiles75",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles75\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "percentiles95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles95\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "percentiles99",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles99\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "Mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  }
 ]
}